import DistinctionStructures.Basic
import DistinctionStructures.Delta1
import DistinctionStructures.Discoverable
import DistinctionStructures.Delta0
import DistinctionStructures.ActualityIrreducibility
import DistinctionStructures.Delta2
import DistinctionStructures.Delta3
