; ═══════════════════════════════════════════════════════════════════════
; Test harness for psi_transpile.lisp — self-hosted Ψ-Lisp transpiler
; ═══════════════════════════════════════════════════════════════════════
;
; Generates a single Rust program that tests all expression types.
; The emitted program prints results one per line.
;
; Usage:
;   python3 psi_lisp.py --table=c examples/psi_transpile_test.lisp | sed '1d;$d' > /tmp/out.rs
;   cp psi_runtime.rs /tmp/
;   rustc -O -o /tmp/out /tmp/out.rs && /tmp/out
;
; Expected output:
;   3
;   42
;   99
;   3
;   5
;   5
; ═══════════════════════════════════════════════════════════════════════

; ── Expression constructors ──────────────────────────────────────────

(defun mk-atom (n)       (cons 0 n))
(defun mk-var (name)     (cons 1 name))
(defun mk-dot (a b)      (cons 2 (cons a b)))
(defun mk-if (test th el)  (cons 3 (cons test (cons th el))))
(defun mk-let (x val body) (cons 4 (cons x (cons val body))))
(defun mk-lam (x body)   (cons 5 (cons x body)))
(defun mk-app (fn arg)   (cons 6 (cons fn arg)))

; ── Expression accessors ─────────────────────────────────────────────

(defun expr-tag (e)   (car e))
(defun expr-payload (e) (cdr e))

(defun dot-a (e) (car (cdr e)))
(defun dot-b (e) (cdr (cdr e)))

(defun if-test (e) (car (cdr e)))
(defun if-then (e) (car (cdr (cdr e))))
(defun if-else (e) (cdr (cdr (cdr e))))

(defun let-var (e)  (car (cdr e)))
(defun let-val (e)  (car (cdr (cdr e))))
(defun let-body (e) (cdr (cdr (cdr e))))

(defun lam-var (e)  (car (cdr e)))
(defun lam-body (e) (cdr (cdr e)))

(defun app-fn (e)  (car (cdr e)))
(defun app-arg (e) (cdr (cdr e)))

; ── Predicates ───────────────────────────────────────────────────────

(defun is-atom (e) (= (expr-tag e) 0))
(defun is-var (e)  (= (expr-tag e) 1))
(defun is-dot (e)  (= (expr-tag e) 2))
(defun is-if (e)   (= (expr-tag e) 3))
(defun is-let (e)  (= (expr-tag e) 4))
(defun is-lam (e)  (= (expr-tag e) 5))
(defun is-app (e)  (= (expr-tag e) 6))

; ── Emission helpers ─────────────────────────────────────────────────

(defun emit-newline () (write-char 10))

(defun emit-int (n)
  (if (< n 10)
      (write-char (+ n 48))
      (begin
        (emit-int (/ n 10))
        (write-char (+ (mod n 10) 48)))))

(defun emit-varname (name)
  (write-string "_v")
  (emit-int name))

; ── Core transpiler ──────────────────────────────────────────────────

(defun transpile-expr (e)
  (cond
    ((is-atom e)
     (begin
       (emit-int (expr-payload e))
       (write-string "_i64")))

    ((is-var e)
     (emit-varname (expr-payload e)))

    ((is-dot e)
     (let ((a (dot-a e))
           (b (dot-b e)))
       (if (and (is-atom a) (= (expr-payload a) 13))
           (begin
             (write-string "psi_inc(")
             (transpile-expr b)
             (write-string " as u8) as PsiVal"))
           (if (and (is-atom a) (= (expr-payload a) 14))
               (begin
                 (write-string "psi_inv(")
                 (transpile-expr b)
                 (write-string " as u8) as PsiVal"))
               (if (and (is-atom a) (= (expr-payload a) 15))
                   (begin
                     (write-string "psi_dec(")
                     (transpile-expr b)
                     (write-string " as u8) as PsiVal"))
                   (begin
                     (write-string "psi_dot(")
                     (transpile-expr a)
                     (write-string " as u8, ")
                     (transpile-expr b)
                     (write-string " as u8) as PsiVal")))))))

    ((is-if e)
     (begin
       (write-string "if (")
       (transpile-expr (if-test e))
       (write-string ") != 1_i64 { ")
       (transpile-expr (if-then e))
       (write-string " } else { ")
       (transpile-expr (if-else e))
       (write-string " }")))

    ((is-let e)
     (begin
       (write-string "{ let ")
       (emit-varname (let-var e))
       (write-string ": PsiVal = ")
       (transpile-expr (let-val e))
       (write-string "; ")
       (transpile-expr (let-body e))
       (write-string " }")))

    ((is-lam e)
     (write-string "PSI_NIL /* bare lambda */"))

    ((is-app e)
     (write-string "PSI_NIL /* bare app */"))

    (T (write-string "PSI_NIL /* unknown */"))))

; ── Multi-expression entry point ─────────────────────────────────────
; Emits a Rust program that evaluates and prints each expression

(defun emit-header ()
  (write-string "// Generated by psi_transpile_test.lisp")
  (emit-newline)
  (write-string "#![allow(non_snake_case, unused_parens, unused_variables)]")
  (emit-newline)
  (write-string "#[path = ")
  (write-char 34)
  (write-string "psi_runtime.rs")
  (write-char 34)
  (write-string "]")
  (emit-newline)
  (write-string "mod psi_runtime;")
  (emit-newline)
  (write-string "use psi_runtime::*;")
  (emit-newline)
  (emit-newline)
  (write-string "fn main() {")
  (emit-newline)
  (write-string "    let arena = Arena::new();")
  (emit-newline))

(defun emit-test (e)
  (write-string "    psi_println(&arena, ")
  (transpile-expr e)
  (write-string ");")
  (emit-newline))

(defun emit-footer ()
  (write-string "}")
  (emit-newline))

; ═══════════════════════════════════════════════════════════════════════
; TESTS
; ═══════════════════════════════════════════════════════════════════════

; Wrap all emission in a single progn to avoid NIL return values
; being printed as top-level results by the Python transpiler
(progn
  (emit-header)
  ; Test 1: dot(INC, f) = INC(2) = 3
  (emit-test (mk-dot (mk-atom 13) (mk-atom 2)))
  ; Test 2: if(TOP, 42, 99) = 42  (TOP=0, not BOT)
  (emit-test (mk-if (mk-atom 0) (mk-atom 42) (mk-atom 99)))
  ; Test 3: if(BOT, 42, 99) = 99  (BOT=1, false)
  (emit-test (mk-if (mk-atom 1) (mk-atom 42) (mk-atom 99)))
  ; Test 4: let x=INC in dot(x, f) = 3
  (emit-test (mk-let 100 (mk-atom 13) (mk-dot (mk-var 100) (mk-atom 2))))
  ; Test 5: dot(INV, f) = INV(2) = 5
  (emit-test (mk-dot (mk-atom 14) (mk-atom 2)))
  ; Test 6: INC(INC(INC(f))) = 5 (nested dot)
  (emit-test (mk-dot (mk-atom 13) (mk-dot (mk-atom 13) (mk-dot (mk-atom 13) (mk-atom 2)))))
  (emit-footer))
